network = "bitcoin"

electrum_rpc_addr = "127.0.0.1:50001"

cookie_file = "/var/lib/bitcoind/.cookie"
db_dir = "/var/lib/electrs"

log_filters = "INFO"

daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"
daemon_dir = "/var/lib/bitcoind"
