server=1

rpccookiefile=/var/lib/bitcoin/.cookie
rpccookieperms=group
rpcbind=127.0.0.1
rpcallowip=127.0.0.1

dnsseed=0
onlynet=onion

bind=127.0.0.1
proxy=127.0.0.1:9050

listen=1
listenonion=1
torcontrol=127.0.0.1:9051

txindex=1

dbcache=1024
